apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      name: my-deployment
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: my-deployment
    spec:
      tolerations:
        - key: "key"
          operator: "Equal"
          value: "value"
          effect: "NoSchedule"
      containers:
        - image: amitgujar/static-app:latest
          name: my-deployment
          resources:
            requests:
              cpu: 15m
              memory: 105M
            limits:
              cpu: 15m
              memory: 105M
          ports:
            - containerPort: 80
              name: http
