apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: amitgujar/static-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - name:  cred-volume
            mountPath:  /etc/creds
            readOnly: true
      volumes:
      - name:  cred-volume
        secret:
          secretName:  db-secrets