apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemonset
  labels:
    app: my-daemonapp
spec:
  selector:
    matchLabels:
      app: my-daemonapp
  template:
    metadata:
      labels:
        app: my-daemonapp
    spec:
      containers:
        - name: my-daemonapp
          image: amitgujar/static-app:latest
          ports:
            - containerPort: 80
              name: web
