apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-deployment
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: affinity-deployment
  template:
    metadata:
      labels:
        app: affinity-deployment
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - affinity-deployment
      containers:
        - name: affinity-deployment
          image: amitgujar/static-app:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: http
